name: Lint, type-check, and test Python code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  pytest:
    name: Test with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install .
      - name: Test with pytest
        run: |
          pytest test
  flake8:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Lint with flake8
        uses: py-actions/flake8@v2.3.0
        with:
          max-line-length: 127
          path: cvrp_metaheuristics
  mypy:
    name: Type-check with mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
      - name: Type-check with mypy
        uses: jpetrucciani/mypy-check@1.10.0
        with:
          requirements_file: requirements-dev.txt
          path: cvrp_metaheuristics